### ISSUE TITLE
"offline" mode?

### ISSUE THREAD

**Issue by njdro** [ExMCL/ExMCL#1]
Requesting an offline mode (no account authentication) for personal servers.

Also, step 8 of build process, it seems you must be `cd`'d into `runmehere/` otherwise it cannot find Minecraft.jar

Lastly, i don't understand why it need two copies of the same file.  could you please explain?  

thank you.

**Comment by n9Mtq4** [comment]
1. I like that idea and will look into it.
2. Of course. The `runmehere` directory is the working directory for testing the launcher. If running from the command line you do have to cd or you could always double click the jar file in the `runmehere`.
3. I guess you are referring to having a copy of `Minecraft.jar` inside the `providedlibs` and the `runmehere` directory. You are correct in that there only needs one copy. The reason why I have it located in both places is that the `providedlibs` directory is for libraries that will be provided at runtime and are only there to be compiled against. While in the `runmehere` directory, `Minecraft.jar` is used to run the launcher. So in summary, to build you need it in `providedlibs` and to run you need it in `runmehere`. Since you want to do both, it is located in both.

**Comment by n9Mtq4** [comment]
After thinking about it I have changed my mind about including such a feature. This is not a cracked launcher. It is rather an API for the minecraft launcher with default plugins to add features. Mojang's launcher has the ability to login offline if you have previously logged in before. Cracking the launcher is most likely illegal and I would rather not have this repo be DMCAed.

If I misunderstood the feature that you would like added please clarify. If you would still like a cracked version, feel free to decompile the launcher (and even use this API, I won't stop you) to create a cracked launcher yourself.

**Comment by njdro** [comment]
Thank you for the consideration none-the-less.  True, i am not an account holder and thusly considered taboo.

I have created a LAN Spigot server for my daughter and she plays it without an account either.  I of course have to "play" to check things too.

Although I would like the feature, i completely understand.
